#!/bin/sh

cd ../config
ssh-keygen -t rsa -P '' -f ./ssh/id_rsa
cat ./ssh/id_rsa.pub >> ./ssh/authorized_keys
kubectl create secret generic ssh-key-secret --from-file=id_rsa=./ssh/id_rsa --from-file=id_rsa.pub=./ssh/id_rsa.pub --from-file=authorized_keys=./ssh/authorized_keys
