apiVersion: v1
kind: Secret
metadata:
  name: mapr-user-secrets
type: Opaque
data:
  MAPR_USER: cm9vdAo=
  MAPR_GROUP: bWFwcg==
  MAPR_UID: NTAwMA==
  MAPR_GID: NTAwMA==
  MAPR_PASSWORD: bWFwcg==
  MAPR_ROOT_PASSWORD: bWFwcg==
