apiVersion: v1
kind: Pod
metadata:
  name: pacc-mssql
spec:
  containers:
  - name: pacc-mssql
    imagePullPolicy: Always
    image: maprhack1.azurecr.io/jameshtsun/pacc-mssql:latest
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN" , "SYS_RESOURCE"]
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      value: "M@prh@ckfest"
    - name: MSSQL_BASE_DIR
      value: "/mnt/my.cluster.com/"
    - name: MAPR_MOUNT_PATH
      value: "/mnt"
    - name: MAPR_MEMORY
      valueFrom:
        resourceFieldRef:
          containerName: pacc-mssql
          resource: requests.memory
    - name: MAPR_CLUSTER
      valueFrom:
        configMapKeyRef:
          name: mapr-cluster-configmap
          key: MAPR_CLUSTER
    - name: MAPR_CLDB_HOSTS
      valueFrom:
        configMapKeyRef:
          name: mapr-cluster-configmap
          key: MAPR_CLDB_HOSTS
    - name: MAPR_TZ
      valueFrom:
        configMapKeyRef:
          name: mapr-cluster-configmap
          key: MAPR_TZ
    - name: MAPR_HOME
      valueFrom:
        configMapKeyRef:
          name: mapr-cluster-configmap
          key: MAPR_HOME
    - name: MAPR_CONTAINER_USER
      valueFrom:
        secretKeyRef:
          name: mapr-user-secrets
          key: MAPR_USER
    - name: MAPR_CONTAINER_GROUP
      valueFrom:
        secretKeyRef:
          name: mapr-user-secrets
          key: MAPR_GROUP
    - name: MAPR_CONTAINER_UID
      valueFrom:
        secretKeyRef:
            name: mapr-user-secrets
            key: MAPR_UID
    - name: MAPR_CONTAINER_GID
      valueFrom:
        secretKeyRef:
          name: mapr-user-secrets
          key: MAPR_GID
    - name: MAPR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mapr-user-secrets
          key: MAPR_PASSWORD
    - name: MAPR_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mapr-user-secrets
          key: MAPR_ROOT_PASSWORD
    volumeMounts:
    - mountPath: /data/jims
      name: jims
    - mountPath: /dev/fuse
      name: fuse
  volumes:
  - name: jims
    emptyDir: {}
  - name: fuse
    hostPath:
      path: /dev/fuse
